[build]
  base = "/opt/build/repo/client/web"
  command = "npm run build"
  publish = "/opt/build/repo/client/web/.next"  # This should be the correct path to .next folder
[[plugins]]
  package = "@netlify/plugin-nextjs"
