name: senior_project
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  socket_io_client: ^2.0.3+1
  image_picker: ^1.1.2
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  google_nav_bar: ^5.0.7
  intl: ^0.18.0
  file_picker: ^10.1.2
  url_launcher: ^6.3.1
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21